sudo: false
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          packages:
            - libsndfile1-dev
            - libasound2-dev
            - libfftw3-dev

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libsndfile1-dev
            - libasound2-dev
            - libfftw3-dev

    - os: osx
      compiler: clang

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install libsndfile
    fi

install:
  - true

script:
  - ./autogen.sh
  - ./configure --enable-werror && make clean all check && make distcheck
